//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public Nullable<int> ReportsTo { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int Expr1 { get; set; }
        public string LastName { get; set; }
        public string FirstNamerep { get; set; }
        public string LastNamerep { get; set; }
        public string Expr3 { get; set; }
    }
}
